# claude-loop.ps1 -- generated by claude-audit install-autorestart
# Run this instead of 'claude'. Sessions rotate automatically when waste hits threshold.
# Usage: .\claude-loop.ps1

$flagPath    = Join-Path $HOME ".claude-audit\restart-flag"
$maxRestarts = 50
$restarts    = 0

if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {
    Write-Host "[claude-loop] ERROR: 'claude' not found in PATH." -ForegroundColor Red
    exit 1
}

Write-Host "[claude-loop] Starting. Auto-restart ON." -ForegroundColor Cyan
Write-Host "[claude-loop] Sessions rotate at waste threshold. Context injected on each start." -ForegroundColor DarkCyan
Write-Host ""

while ($restarts -lt $maxRestarts) {
    # cmd /c handles .cmd shims and inherits the current console (proper interactive TUI)
    cmd /c claude

    if (Test-Path $flagPath) {
        Remove-Item $flagPath -Force -ErrorAction SilentlyContinue
        $restarts++
        Write-Host ""
        Write-Host "[claude-loop] Session rotated ($restarts/$maxRestarts). Restarting..." -ForegroundColor Cyan
        Start-Sleep -Milliseconds 800
    } else {
        Write-Host ""
        Write-Host "[claude-loop] Session ended normally." -ForegroundColor Green
        break
    }
}

if ($restarts -ge $maxRestarts) {
    Write-Host "[claude-loop] Safety ceiling reached ($maxRestarts restarts). Exiting." -ForegroundColor Yellow
}
