# claude-loop.ps1 -- generated by entient-spend install-autorestart
# Run this instead of 'claude'. Sessions rotate automatically when waste hits threshold.
#
# Usage:
#   .\claude-loop.ps1                  # restart in same window (default)
#   .\claude-loop.ps1 -NewWindow       # open a fresh PowerShell window on each restart
#
# How it works:
#   1. Launches claude interactively (cmd /c for proper .cmd shim + TTY)
#   2. When entient-spend detects 5x waste: kills claude, writes restart-flag
#   3. This script detects the flag, waits, relaunches claude
#   4. New session's SessionStart hook auto-injects last-session.md context
#   5. Human out of the loop -- fully automatic

param(
    [switch]$NewWindow,         # open new PS window on restart instead of reusing this one
    [int]$MaxRestarts = 50      # safety ceiling
)

$flagPath    = Join-Path $HOME ".entient-spend\restart-flag"
$contextPath = Join-Path $HOME ".entient-spend\last-session.md"
$thisScript  = $MyInvocation.MyCommand.Path
$restarts    = 0

if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {
    Write-Host "[claude-loop] ERROR: 'claude' not found in PATH." -ForegroundColor Red
    exit 1
}

function Show-Banner {
    Write-Host "[claude-loop] Auto-restart ON. Waste threshold: 5x." -ForegroundColor Cyan
    Write-Host "[claude-loop] Context saved + injected automatically on rotation." -ForegroundColor DarkCyan
    if ($NewWindow) {
        Write-Host "[claude-loop] Mode: new window on each restart." -ForegroundColor DarkCyan
    }
    Write-Host ""
}

Show-Banner

while ($restarts -lt $MaxRestarts) {
    # Heap headroom for long-running sessions. V8 default heap on Windows
    # crashed long sessions with "Committing semi space failed" after ~24h.
    # 4GB old-space leaves room for the Python worker pool on 16GB machines.
    $env:NODE_OPTIONS = "--max-old-space-size=4096"

    # cmd /c: resolves .cmd shims (npm-installed claude) and inherits the current console
    # so the TUI renders correctly with full color + input
    cmd /c claude

    if (Test-Path $flagPath) {
        $flagData = Get-Content $flagPath -Raw -ErrorAction SilentlyContinue
        $factor   = "?"
        try {
            $info   = $flagData | ConvertFrom-Json
            $factor = $info.factor
        } catch {}

        Remove-Item $flagPath -Force -ErrorAction SilentlyContinue
        $restarts++

        Write-Host ""
        Write-Host "[claude-loop] Session rotated ($restarts/$MaxRestarts) -- waste was ${factor}x." -ForegroundColor Yellow

        if (Test-Path $contextPath) {
            Write-Host "[claude-loop] Context saved -> will be injected into next session." -ForegroundColor Green
        }

        if ($NewWindow) {
            # Open a fresh PowerShell window running this same script, then exit this one
            Write-Host "[claude-loop] Opening new window in 2s..." -ForegroundColor Cyan
            Start-Sleep -Seconds 2
            Start-Process powershell.exe -ArgumentList `
                "-NoExit -ExecutionPolicy Bypass -File `"$thisScript`" $(if ($NewWindow) { '-NewWindow' })"
            Write-Host "[claude-loop] New window launched. This window will close." -ForegroundColor Gray
            Start-Sleep -Seconds 1
            exit 0
        } else {
            # Restart in same window after brief pause
            Write-Host "[claude-loop] Restarting in 2s... (Ctrl+C to cancel)" -ForegroundColor Cyan
            Start-Sleep -Seconds 2
            Write-Host ""
            Show-Banner
        }
    } else {
        Write-Host ""
        Write-Host "[claude-loop] Session ended normally." -ForegroundColor Green
        break
    }
}

if ($restarts -ge $MaxRestarts) {
    Write-Host "[claude-loop] Safety ceiling reached ($MaxRestarts restarts). Exiting." -ForegroundColor Yellow
}
